Repository jitacm/30_days_java-P2P-, pull requests merged in 2025-08, with the labels that each got.

#5 Complete README.md Overhaul - From Confusing to User-Friendly
  README.md
Labels: documentation, 30daysdevchallenge, jitacm, level-2

#6 Add Comprehensive README Documentation for Java-P2P File Sharer
  README.md
Labels: documentation, 30daysdevchallenge, jitacm, level-2

#8 feat: Add Peer Discovery and Download Resume
  P2P java/PeerDiscoveryService.java
  P2P java/peer.java
Labels: 30daysdevchallenge, jitacm, feature, level-3

#10 Add SHA-256 checksum verification for file downloads
  P2P java/peer.java
Labels: 30daysdevchallenge, jitacm, feature, level-2

#12 Added a new Swing-based GUI with progress bar and file list
  P2P java/PeerGUI.java
  P2P java/peer.java
Labels: 30daysdevchallenge, jitacm, uiux, level-4

#19 Implementing GUI Power Features for P2P Java Application #18
  P2P java/PeerGUI.java
  P2P java/peer.java
Labels: 30daysdevchallenge, jitacm, uiux, level-3
